# URL de conexão (Adicionado parâmetros para criar o banco automaticamente e evitar avisos de fuso horário)
spring.datasource.url=${BD_CONEXAO}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate / JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# Dialeto atualizado para versões modernas do Spring Boot / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Configurações de Documentação e Aplicação (Corrigido o erro de espaçamento)
springdoc.override-with-generic-response=false
spring.application.name=bancofel
